package com.example.testBoard.testStudy.class5;

import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.transaction.Transactional;

import org.aspectj.lang.annotation.Around;
import org.springframework.beans.factory.annotation.Autowired;

/*

참고자료
1. h2 database설치
https://atoz-develop.tistory.com/entry/H2-Database-%EC%84%A4%EC%B9%98-%EC%84%9C%EB%B2%84-%EC%8B%A4%ED%96%89-%EC%A0%91%EC%86%8D-%EB%B0%A9%EB%B2%95

2. lombok
설치
https://dololak.tistory.com/783
댓참고 - 실무에서 롬복사용, 주의점
https://hello-world.tistory.com/8

오류사항
1. org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-200]
-> 스프링부트 2.4부터는 application.properties에 `spring.datasource.username=sa`를 꼭 추가
2.java.lang.NullPointerException: Cannot invoke "javax.persistence.EntityManager.createQuery(String, java.lang.Class)" because "this.em" is null
	private EntityManager em;
	
	@Autowired
	public SpringConfig(EntityManager em) {
		this.em = em;
	}
3. org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "ID"; SQL statement:
insert into member (id, name) values (null, ?) [23502-200]
//implementation 'org.springframework.boot:spring-boot-starter-jdbc'
H2 1.4.200 버전을 사용해주세요. -> h2 신버전에서 발생하는 오류입니다.

4. Caused by: java.lang.IllegalArgumentException: Pointcut is not well-formed: expecting ')' at character position 13
executinon(* com.example.testBoard..*(..))

Caused by: java.lang.IllegalArgumentException: Pointcut is not well-formed: expecting 'name pattern' at character position 53
execution(*com.example.testBoard.testStudy.class5..*(..))
-> @Around("execution(* com.example.testBoard..*(..))")
                                                     
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Connection is broken: "java.net.ConnectException: Connection refused: no further information: localhost" [90067-200]
-> h2재기동

5. 롬복 설치시 ide못찾음
DI :1.18.12 추가 -> 안됨
C:\Users\JYH\.m2\repository\org\projectlombok\lombok\1.18.2 가이드의 위경로가 아니었음
C:\Users\JYH\.gradle\caches\modules-2\files-2.1\org.projectlombok\lombok\1.18.22\9c08ea24c6eb714e2d6170e8122c069a0ba9aacf

6. 롬복 설치후 패키지오류 enum~~ 
소스 재복붙

구현목표
1. Memory -> H2 databas로 연결
1-1. h2 database설치
bin/h2.bat
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

1-2. build.gradle
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	runtimeOnly 'com.h2database:h2'
1-3. application.properties
	spring.datasource.url=jdbc:h2:tcp://localhost/~/test
	spring.datasource.driver-class-name=org.h2.Driver

1-1. 순수Jdbc
JdbcMemberRepository 생성, SpringConfig 수정
1-2. 스프링Jdbc템플릿
JdbcTemplateMemberRepository 생성, SpringConfig 수정
application.properties - spring.datasource.username=sa
1-3. JPA
JpaMemberRepository 생성, SpringConfig 수정

implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

service -> @Transactional 추가
member -> @Entity
public class Member {

	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
	//@Column(name="username")
    private String name;
    
   
1-4. 스프링데이터 JPA
SpringDataJpaMemberRepository생성, SpringConfig수정

2. aop
TimeTraceAop생성

3.lombok
	compileOnly 'org.projectlombok:lombok:1.18.12'
    annotationProcessor 'org.projectlombok:lombok:1.18.12'
    testCompileOnly 'org.projectlombok:lombok:1.18.12'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.12'
    
  C:\Users\JYH\.gradle\caches\modules-2\files-2.1\org.projectlombok\lombok\1.18.22\9c08ea24c6eb714e2d6170e8122c069a0ba9aacf -> java -jar lombok-1.18.22.jar
  
  
*/